# Generated by Django 4.0.4 on 2022-05-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsonData',
        ),
    ]
